/*
* Definition and implementation of the abstract syntax tree (AST) that will be
* generated by the parser.
----------------------------------------------------------------------------
*
* All nodes will implement the "Node" interface
*/

package parser

import (
	"fmt"

	"github.com/hasnainzeenwala/hzglox/lexer"
)

// =============================================================================
// Node Interface Definition
// =============================================================================
type Node interface {
	// Just a marker not expected to have any implementation
	IsNode()
	// Self-explanatory
	PrintAst() string
	// Evaluate/execute a subtree
	Interpret() (val any, err error)
}




// =============================================================================
// Node Interface Implementation
// =============================================================================

// -- LiteralNode -> NUMBER | STRING | true | false | nil ; --
// ----------------------------------------------------------------------------
type LiteralNode struct {
	T lexer.Token
}

func (l *LiteralNode) IsNode() {}

func (l *LiteralNode) PrintAst() string {
	return l.T.Lexeme
}

func (l *LiteralNode) Interpret() (any, error) {
	return l.T.Literal, nil
}


// -- GroupingNode -> "(" expression ")" ; --
// -----------------------------------------------------------------------------
type GroupingNode struct {
	E Node
}

func (g *GroupingNode) IsNode() {}

func (g *GroupingNode) PrintAst() string {
	return "( group " + g.E.PrintAst() + " )"
}

func (g *GroupingNode) Interpret() (any, error) {
	return g.E.Interpret()
}


// -- UnaryNode -> ( "-" | "!" ) expression ; --
// ----------------------------------------------------------------------------
type UnaryNode struct {
	T lexer.Token
	E Node
}

func (u *UnaryNode) IsNode() {}

func (u *UnaryNode) PrintAst() string {
	return "( " + u.T.Lexeme + u.E.PrintAst() + " )"
}

func (u *UnaryNode) Interpret() (any, error) {
	v, err := u.E.Interpret()
	if err != nil {
		return nil, err
	}
	if u.T.TType == lexer.Minus {
		vfloat, isFLoat := v.(float64)
		if !isFLoat {
			return nil, fmt.Errorf("Expected a number but found something else %v", v)
		}
		return -vfloat, nil
	} else if u.T.TType == lexer.Bang {
		vbool, err := InterpretAsBoolean(v)
		if err != nil {
			return nil, err
		}
		return !vbool, nil
	}
	return nil, fmt.Errorf("Unexpected unary operator. Expected '-' or '!'. Got %s", u.T.Lexeme)
}


// -- Binary -> expression op expression ; --
// ------------------------------------------------------------------------------------
type Binary struct {
	Le Node
	Op lexer.Token
	Re Node
}

func (b *Binary) IsNode() {}

func (b *Binary) PrintAst() string {
	return "( " + b.Op.Lexeme + " " + b.Le.PrintAst() + " " + b.Re.PrintAst() + " )"
}

func (b *Binary) Interpret() (any, error) {
	return nil, nil
}




// =======================================================================================
// Helper functions
// =======================================================================================
func IsLiteral(t lexer.Token) bool {
	return t.TType == lexer.Number || t.TType == lexer.String ||
		t.TType == lexer.True || t.TType == lexer.False || t.TType == lexer.Nil
}

func IsLeftParen(t lexer.Token) bool {
	return t.TType == lexer.LeftParen
}

func IsRightParen(t lexer.Token) bool {
	return t.TType == lexer.RightParen
}

func IsMinus(t lexer.Token) bool {
	return t.TType == lexer.Minus
}

func IsBang(t lexer.Token) bool {
	return t.TType == lexer.Bang
}

func IsOperator(t lexer.Token) bool {
	return t.TType == lexer.EqualEqual || t.TType == lexer.BangEqual ||
		t.TType == lexer.Less || t.TType == lexer.LessEqual || t.TType == lexer.Greater ||
		t.TType == lexer.GreaterEqual || t.TType == lexer.Star || t.TType == lexer.Minus ||
		t.TType == lexer.Plus || t.TType == lexer.Slash
}

// Tries to interpret the supplied value as a boolean.
// if it can't it returns an error.
func InterpretAsBoolean(v any) (bool, error) {
	if v == nil {
		return false, nil
	}
	vbool, isBool := v.(bool)
	if isBool {
		return vbool, nil
	}
	vString, isString := v.(string)
	if isString && (vString == "") {
		return false, nil
	}
	return false, fmt.Errorf("Value can't be interpreted as a boolean %v", v)
}
